# Generated by Django 6.0.4 on 2026-04-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='website_url',
            field=models.URLField(max_length=500),
        ),
    ]
