# Generated by Django 6.0.4 on 2026-04-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alertsettings_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
